### ISSUE TITLE
无法下载图片

### ISSUE THREAD

**Issue by greenhandzdl** [CaliGrosto/SimpleSendPhoto#2]
```
2022-07-30 13:57:56 V/Bot.742431945: GWS Tech.L(2029252158) -> /添加图片 新人 [mirai:image:{4A7D335C-2D32-3F9A-9B1B-1FAC98D8BA8A}.jpg, width=250, height=284, size=15535, type=JPG, isEmoji=true]
2022-07-30 13:57:57 W/SimpleSendPhoto: Exception in executing command `[mirai:source:ids=[24213], internalIds=[1606708816], from friend 2029252158 to 742431945 at 1659189475]/添加图片 新人 [mirai:image:{4A7D335C-2D32-3F9A-9B1B-1FAC98D8BA8A}.jpg, width=250, height=284, size=15535, type=JPG, isEmoji=true]`
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:194)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.FileNotFoundException: 请修改/新人.jpg (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at SimpleSendPhoto-V1.5.jar//com.example.Util.savePictures.SavePicture(savePictures.java:34)
        at SimpleSendPhoto-V1.5.jar//com.example.Command.UploadPictures.onCommand(UploadPictures.java:21)
        ... 21 more
```

**Comment by CaliGrosto** [comment]
是不是没有修改配置文件。

**Comment by CaliGrosto** [comment]
Caused by: java.io.FileNotFoundException: 请修改/新人.jpg (No such file or directory)
这问题应该是图库4的路径没有更改吧。

**Comment by greenhandzdl** [comment]
```
SavePicture: 'data/Picture/SavePicture.jpg'     #默认不要修改
```
不太能理解save目录不就是这个吗

**Comment by CaliGrosto** [comment]
SavePicture: 'data/Picture/SavePicture.jpg'     #默认不要修改
这不是save目录，这是另外一个功能用到的..是存放从loliconapi获取到的图片的目录

群内添加图片会添加到 PicturePath4 指向的路径
README上面应该写的挺清楚了
